steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cover-letter-backend-image:$COMMIT_SHA', './backend/app']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cover-letter-backend-image:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'cover-letter-backend',
    '--image', 'gcr.io/$PROJECT_ID/cover-letter-backend-image:$COMMIT_SHA',
    '--platform', 'managed',
    '--region', 'us-central1',
    '--allow-unauthenticated'
  ]

images:
- 'gcr.io/$PROJECT_ID/cover-letter-backend-image:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
